;==============================================================================;
;                         ictOS Crash System constents                         ;
;                                                                      by: ict ;
;==============================================================================;

LOCATION_EAX        equ     0x1e9
LOCATION_EDX        equ     0x1fd
LOCATION_ECX        equ     0x211
LOCATION_EBX        equ     0x225
LOCATION_ESP        equ     0x239
LOCATION_EBP        equ     0x24d
LOCATION_ESI        equ     0x261
LOCATION_EDI        equ     0x275
LOCATION_EIP        equ     0x6a8
LOCATION_CS         equ     0x698
LOCATION_SS         equ     0x2e7
LOCATION_DS         equ     0x2f6
LOCATION_ES         equ     0x2d8
LOCATION_GS         equ     0x314
LOCATION_FS         equ     0x305
LOCATION_EFLAGS     equ     0x37a
LOCATION_CR0        equ     0x417
LOCATION_CR2        equ     0x467
LOCATION_CR3        equ     0x4b7
LOCATION_GDTR_BASE  equ     0x5b0
LOCATION_GDTR_LIMIT equ     0x5c4
LOCATION_IDTR_BASE  equ     0x600
LOCATION_IDTR_LIMIT equ     0x614
LOCATION_ERROR_CODE equ     0x185
LOCATION_ERROR_MSG  equ     0x142

ERROR_MSG_LEN       equ     0x36
