;==============================================================================;
;                               ictOS BIOS Color                               ;
;                                                                      by: ict ;
;==============================================================================;

;\
| color name |________________| data |
color_black             equ     0x0
color_blue              equ     0x1
color_green             equ     0x2
color_cyan              equ     0x3
color_red               equ     0x4
color_magenta           equ     0x5
color_brown             equ     0x6
color_lightgray         equ     0x7
color_darkgray          equ     0x8
color_lightblue         equ     0x9
color_lightgreen        equ     0xa
color_lightcyan         equ     0xb
color_lightred          equ     0xc
color_lightmagenta      equ     0xd
color_yellow            equ     0xe
color_white             equ     0xf
color_b_black           equ     0x00
color_b_blue            equ     0x10
color_b_green           equ     0x20
color_b_cyan            equ     0x30
color_b_red             equ     0x40
color_b_magenta         equ     0x50
color_b_brown           equ     0x60
color_b_lightgray       equ     0x70
