;==============================================================================;
;                            ictOS VGA I/O Ports                               ;
;                                                                      by: ict ;
;==============================================================================;

CURSOR_HIGH     equ     0xe
CURSOR_LOW      equ     0xf
START_HIGH      equ     0xc
START_LOW       equ     0xd
CRTCR_ADDR      equ     0x3d4
CRTCR_DATA      equ     0x3d5
