;==============================================================================;
;                          ictOS 1.00 sysboot header                           ;
;                                                                      by: ict ;
;==============================================================================;

BOOT_OFFSET         equ 0x7c00
BOOT_BLOCK_OFFSET   equ 0x600
BOOT_BLOCK_SIZE     equ 0x4
BOOT_BLOCK_ADDR     equ 0x1
